import '../../../../services/app_database.dart';
import '../../domain/entities/session_entity.dart';
import '../../domain/entities/session_summary_entity.dart';

/// Data model for [SessionSummaryEntity] that adds serialization
/// from Drift database rows.
class SessionSummaryModel extends SessionSummaryEntity {
  /// Creates a [SessionSummaryModel].
  const SessionSummaryModel({
    required super.id,
    required super.languageCode,
    required super.createdAt,
    required super.durationMs,
    required super.previewText,
    required super.hasRefinedText,
    required super.audioFilePath,
    required super.status,
  });

  /// Creates a [SessionSummaryModel] from a Drift [Session] data class.
  ///
  /// The [previewText] is generated by taking the first 100 characters
  /// of [transcribedText] and appending "..." if longer.
  factory SessionSummaryModel.fromDrift(Session driftSession) {
    final text = driftSession.transcribedText;
    final preview = text.length > 100 ? '${text.substring(0, 100)}...' : text;

    return SessionSummaryModel(
      id: driftSession.id,
      languageCode: driftSession.languageCode,
      createdAt: driftSession.createdAt,
      durationMs: driftSession.durationMs,
      previewText: preview.isEmpty ? '(No transcription)' : preview,
      hasRefinedText: driftSession.refinedText != null && driftSession.refinedText!.isNotEmpty,
      audioFilePath: driftSession.audioFilePath,
      status: SessionStatus.values[driftSession.status.clamp(0, SessionStatus.values.length - 1)],
    );
  }

  /// Creates a [SessionSummaryModel] from a full [SessionEntity].
  ///
  /// Useful when converting from detail view to list view representation.
  factory SessionSummaryModel.fromEntity(SessionEntity entity) {
    final preview = entity.transcribedText.length > 100
        ? '${entity.transcribedText.substring(0, 100)}...'
        : entity.transcribedText;

    return SessionSummaryModel(
      id: entity.id,
      languageCode: entity.languageCode,
      createdAt: entity.createdAt,
      durationMs: entity.durationMs,
      previewText: preview.isEmpty ? '(No transcription)' : preview,
      hasRefinedText: entity.refinedText != null && entity.refinedText!.isNotEmpty,
      audioFilePath: entity.audioFilePath,
      status: entity.status,
    );
  }

  /// Converts this model to a [SessionEntity].
  ///
  /// Note: [transcribedText] will be reconstructed from [previewText]
  /// without the truncation suffix. For full fidelity, fetch from DB.
  SessionEntity toEntity() {
    final cleanPreview = previewText.endsWith('...')
        ? previewText.substring(0, previewText.length - 3)
        : previewText;

    return SessionEntity(
      id: id,
      languageCode: languageCode,
      createdAt: createdAt,
      updatedAt: createdAt,
      transcribedText: cleanPreview,
      refinedText: null,
      audioFilePath: audioFilePath,
      durationMs: durationMs,
      status: status,
    );
  }
}
